//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBook()
        {
            this.TBLMovement = new HashSet<TBLMovement>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<byte> BookCategory { get; set; }
        public Nullable<int> BookAuthor { get; set; }
        public string BookPublicationYear { get; set; }
        public string BookPublisher { get; set; }
        public string BookPageNumber { get; set; }
        public Nullable<bool> BookStatus { get; set; }
    
        public virtual TBLAuthor TBLAuthor { get; set; }
        public virtual TBLCategory TBLCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMovement> TBLMovement { get; set; }
    }
}
