//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCriminal
    {
        public int CriminalID { get; set; }
        public Nullable<int> CriminalUser { get; set; }
        public Nullable<System.DateTime> CriminalStartDate { get; set; }
        public Nullable<System.DateTime> CriminalEndDate { get; set; }
        public Nullable<decimal> CriminalMoney { get; set; }
        public Nullable<int> CriminalMovement { get; set; }
    
        public virtual TBLMovement TBLMovement { get; set; }
        public virtual TBLUser TBLUser { get; set; }
    }
}
