//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMovement()
        {
            this.TBLCriminal = new HashSet<TBLCriminal>();
        }
    
        public int MovementID { get; set; }
        public Nullable<int> MovementBook { get; set; }
        public Nullable<int> MovementUser { get; set; }
        public Nullable<int> MovementEmployee { get; set; }
        public Nullable<System.DateTime> MovementPurchaseDate { get; set; }
        public Nullable<System.DateTime> MovementReturnDate { get; set; }
    
        public virtual TBLBook TBLBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCriminal> TBLCriminal { get; set; }
        public virtual TBLUser TBLUser { get; set; }
    }
}
