//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAdmin
    {
        public int AdminID { get; set; }
        public string AdminMail { get; set; }
        public string AdminRol { get; set; }
        public string AdminPassword { get; set; }
        public string AdminPhoto { get; set; }
        public Nullable<bool> AdminStatus { get; set; }
    }
}
