//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLComment
    {
        public int CommentID { get; set; }
        public string CommentMail { get; set; }
        public string CommentContent { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<bool> CommentApproval { get; set; }
        public Nullable<bool> CommentStatus { get; set; }
        public string CommentUserPhoto { get; set; }
        public string CommentUserName { get; set; }
        public string CommentUserSurname { get; set; }
        public string CommentUserSchool { get; set; }
    }
}
